x-development-volumes: &development-volumes
  volumes:
    - ../../../docs:/workspace/app/docs/
    - ../../../tools:/workspace/app/tools/
    - ../../../src:/workspace/app/src/
    - ../../../Makefile:/workspace/app/Makefile
    - ../../../pyproject.toml:/workspace/app/pyproject.toml
    - ../../../uv.lock:/workspace/app/uv.lock
    - .env.docker:/workspace/app/.env

services:
  app:
    build:
      context: ../../..
      dockerfile: tools/deploy/docker/Dockerfile.dev
    ports:
      - "8000:8000"
      - "3006:3006"
    tty: true
    environment:
      VITE_DEV_MODE: "true"
      VITE_PORT: "3006"
      SAQ_USE_SERVER_LIFESPAN: "false"
    command: litestar run --reload --host 0.0.0.0 --port 8000
    restart: always
    <<: *development-volumes
  worker:
    build:
      context: ../../..
      dockerfile: tools/deploy/docker/Dockerfile.dev
    command: litestar workers run
    tty: true
    restart: always
    <<: *development-volumes
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy

    env_file:
      - .env.docker
  migrator:
    build:
      context: ../../..
      dockerfile: tools/deploy/docker/Dockerfile.dev
    command: litestar database upgrade --no-prompt
    restart: "no"
    <<: *development-volumes
    env_file:
      - .env.docker
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
